name: lockfile
description: a lockfile utility that works on a local or network file system.
version: 1.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  path: ^1.9.0
  retry: ^3.1.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
